# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Copyright (c) 2026 Arthur Michon
# See LICENSE for terms; COMMERCIAL_LICENSE.md for commercial use.
"""Brand repository contract."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from domain.entities.brand import Brand


class IBrandRepository(Protocol):
    async def get_by_id(self, brand_id: UUID) -> Brand | None: ...
    async def get_by_slug(self, slug: str) -> Brand | None: ...
    async def get_by_name(self, name: str) -> Brand | None: ...
    async def add(self, brand: Brand) -> Brand: ...
    async def update(self, brand: Brand) -> Brand: ...
    async def list_all(self, limit: int = 100, offset: int = 0) -> Sequence[Brand]: ...
    async def count(self) -> int: ...
