"""add media_blob and refactor media_asset

Revision ID: 41ec706668a5
Revises: d1e416a9c5d7
Create Date: 2026-05-25 02:22:25.751732+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ec706668a5'
down_revision: str | Sequence[str] | None = 'd1e416a9c5d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_blob',
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('content_hash', name=op.f('pk_media_blob'))
    )
    op.add_column('media_asset', sa.Column('media_blob_hash', sa.String(length=128), nullable=True))
    op.drop_index(op.f('ix_media_asset_content_hash'), table_name='media_asset')
    op.create_index(op.f('ix_media_asset_media_blob_hash'), 'media_asset', ['media_blob_hash'], unique=False)
    op.create_foreign_key(op.f('fk_media_asset_media_blob_hash_media_blob'), 'media_asset', 'media_blob', ['media_blob_hash'], ['content_hash'], ondelete='SET NULL')
    op.drop_column('media_asset', 'mime_type')
    op.drop_column('media_asset', 'width_px')
    op.drop_column('media_asset', 'quality_score')
    op.drop_column('media_asset', 'byte_size')
    op.drop_column('media_asset', 'height_px')
    op.drop_column('media_asset', 'local_path')
    op.drop_column('media_asset', 'content_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_asset', sa.Column('content_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('media_asset', sa.Column('local_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('media_asset', sa.Column('height_px', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media_asset', sa.Column('byte_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media_asset', sa.Column('quality_score', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True))
    op.add_column('media_asset', sa.Column('width_px', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media_asset', sa.Column('mime_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_media_asset_media_blob_hash_media_blob'), 'media_asset', type_='foreignkey')
    op.drop_index(op.f('ix_media_asset_media_blob_hash'), table_name='media_asset')
    op.create_index(op.f('ix_media_asset_content_hash'), 'media_asset', ['content_hash'], unique=True)
    op.drop_column('media_asset', 'media_blob_hash')
    op.drop_table('media_blob')
    # ### end Alembic commands ###
