"""initial schema

Revision ID: 9f344dbacb5c
Revises: 
Create Date: 2026-05-24 19:41:36.814627+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f344dbacb5c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_origin', sa.String(length=3), nullable=True),
    sa.Column('parent_company', sa.String(length=255), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand'))
    )
    op.create_index(op.f('ix_brand_slug'), 'brand', ['slug'], unique=True)
    op.create_table('customs_price_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('homologation_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('bo_reference', sa.String(length=128), nullable=True),
    sa.Column('raw_brand_label', sa.String(length=255), nullable=False),
    sa.Column('raw_product_label', sa.String(length=255), nullable=False),
    sa.Column('packaging_description', sa.String(length=255), nullable=True),
    sa.Column('unit_price_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pack_size', sa.Integer(), nullable=True),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.Column('tax_class', sa.String(length=64), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customs_price_entry'))
    )
    op.create_index(op.f('ix_customs_price_entry_effective_date'), 'customs_price_entry', ['effective_date'], unique=False)
    op.create_index(op.f('ix_customs_price_entry_raw_brand_label'), 'customs_price_entry', ['raw_brand_label'], unique=False)
    op.create_index(op.f('ix_customs_price_entry_raw_product_label'), 'customs_price_entry', ['raw_product_label'], unique=False)
    op.create_table('cigar_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('is_limited_edition', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', sa.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name=op.f('fk_cigar_line_brand_id_brand'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cigar_line')),
    sa.UniqueConstraint('brand_id', 'slug', name='uq_cigar_line_brand_id_slug')
    )
    op.create_index(op.f('ix_cigar_line_brand_id'), 'cigar_line', ['brand_id'], unique=False)
    op.create_table('cigar',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('vitola_name', sa.String(length=120), nullable=False),
    sa.Column('vitola_factory_name', sa.String(length=120), nullable=True),
    sa.Column('format_category', sa.Enum('ROBUSTO', 'TORO', 'CORONA', 'PETIT_CORONA', 'GRAN_CORONA', 'DOUBLE_CORONA', 'CHURCHILL', 'LONSDALE', 'LANCERO', 'PANETELA', 'PERFECTO', 'TORPEDO', 'BELICOSO', 'FIGURADO', 'DEMI_TASSE', 'OTHER', name='format_category'), nullable=False),
    sa.Column('length_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ring_gauge', sa.Integer(), nullable=True),
    sa.Column('ring_gauge_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weight_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('draw_resistance_cmh2o', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wrapper_country', sa.String(length=3), nullable=True),
    sa.Column('binder_country', sa.String(length=3), nullable=True),
    sa.Column('filler_countries', sa.ARRAY(sa.String(length=3)), nullable=False),
    sa.Column('strength', sa.Enum('MILD', 'MILD_MEDIUM', 'MEDIUM', 'MEDIUM_FULL', 'FULL', name='intensity_strength'), nullable=True),
    sa.Column('body', sa.Enum('MILD', 'MILD_MEDIUM', 'MEDIUM', 'MEDIUM_FULL', 'FULL', name='intensity_body'), nullable=True),
    sa.Column('flavor_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aging_potential_years', sa.Integer(), nullable=True),
    sa.Column('is_cuban', sa.Boolean(), nullable=False),
    sa.Column('is_handmade', sa.Boolean(), nullable=False),
    sa.Column('is_box_pressed', sa.Boolean(), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('discontinued_year', sa.Integer(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['cigar_line.id'], name=op.f('fk_cigar_line_id_cigar_line'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cigar'))
    )
    op.create_index(op.f('ix_cigar_line_id'), 'cigar', ['line_id'], unique=False)
    op.create_index(op.f('ix_cigar_slug'), 'cigar', ['slug'], unique=True)
    op.create_table('blend_component',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cigar_id', sa.Uuid(), nullable=False),
    sa.Column('component_type', sa.Enum('WRAPPER', 'BINDER', 'FILLER_SECO', 'FILLER_VOLADO', 'FILLER_LIGERO', 'FILLER_MEDIO_TIEMPO', name='blend_component_type'), nullable=False),
    sa.Column('tobacco_origin', sa.String(length=120), nullable=True),
    sa.Column('tobacco_region', sa.String(length=120), nullable=True),
    sa.Column('tobacco_variety', sa.String(length=120), nullable=True),
    sa.Column('aging_years', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNVERIFIED', name='confidence'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigar.id'], name=op.f('fk_blend_component_cigar_id_cigar'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blend_component'))
    )
    op.create_index(op.f('ix_blend_component_cigar_id'), 'blend_component', ['cigar_id'], unique=False)
    op.create_table('cigar_customs_match',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cigar_id', sa.Uuid(), nullable=False),
    sa.Column('customs_entry_id', sa.Uuid(), nullable=False),
    sa.Column('match_method', sa.Enum('EXACT', 'FUZZY', 'EMBEDDING', 'MANUAL', name='match_method'), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNVERIFIED', name='confidence_match'), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matched_by', sa.String(length=128), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigar.id'], name=op.f('fk_cigar_customs_match_cigar_id_cigar'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customs_entry_id'], ['customs_price_entry.id'], name=op.f('fk_cigar_customs_match_customs_entry_id_customs_price_entry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cigar_customs_match')),
    sa.UniqueConstraint('cigar_id', 'customs_entry_id', name='uq_cigar_customs_match_cigar_entry')
    )
    op.create_index(op.f('ix_cigar_customs_match_cigar_id'), 'cigar_customs_match', ['cigar_id'], unique=False)
    op.create_index(op.f('ix_cigar_customs_match_customs_entry_id'), 'cigar_customs_match', ['customs_entry_id'], unique=False)
    op.create_table('media_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cigar_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.Enum('FRONT', 'BAND', 'FOOT', 'BOX_CLOSED', 'BOX_OPEN', 'LIFESTYLE', 'ASH', name='media_asset_type'), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OK', 'FAILED', 'QUARANTINED', name='media_status'), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(width_px IS NULL) = (height_px IS NULL)', name=op.f('ck_media_asset_width_height_paired')),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigar.id'], name=op.f('fk_media_asset_cigar_id_cigar'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_asset'))
    )
    op.create_index(op.f('ix_media_asset_cigar_id'), 'media_asset', ['cigar_id'], unique=False)
    op.create_index(op.f('ix_media_asset_content_hash'), 'media_asset', ['content_hash'], unique=True)
    op.create_table('source_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cigar_id', sa.Uuid(), nullable=True),
    sa.Column('source_domain', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_html_hash', sa.String(length=128), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigar.id'], name=op.f('fk_source_record_cigar_id_cigar'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_record'))
    )
    op.create_index(op.f('ix_source_record_cigar_id'), 'source_record', ['cigar_id'], unique=False)
    op.create_index(op.f('ix_source_record_source_domain'), 'source_record', ['source_domain'], unique=False)
    op.create_table('tasting_note',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cigar_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_scale', sa.String(length=64), nullable=True),
    sa.Column('notes_text', sa.Text(), nullable=True),
    sa.Column('notes_structured', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pairing_recommendations', sa.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigar.id'], name=op.f('fk_tasting_note_cigar_id_cigar'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source_record.id'], name=op.f('fk_tasting_note_source_id_source_record'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasting_note'))
    )
    op.create_index(op.f('ix_tasting_note_cigar_id'), 'tasting_note', ['cigar_id'], unique=False)
    op.create_index(op.f('ix_tasting_note_source_id'), 'tasting_note', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasting_note_source_id'), table_name='tasting_note')
    op.drop_index(op.f('ix_tasting_note_cigar_id'), table_name='tasting_note')
    op.drop_table('tasting_note')
    op.drop_index(op.f('ix_source_record_source_domain'), table_name='source_record')
    op.drop_index(op.f('ix_source_record_cigar_id'), table_name='source_record')
    op.drop_table('source_record')
    op.drop_index(op.f('ix_media_asset_content_hash'), table_name='media_asset')
    op.drop_index(op.f('ix_media_asset_cigar_id'), table_name='media_asset')
    op.drop_table('media_asset')
    op.drop_index(op.f('ix_cigar_customs_match_customs_entry_id'), table_name='cigar_customs_match')
    op.drop_index(op.f('ix_cigar_customs_match_cigar_id'), table_name='cigar_customs_match')
    op.drop_table('cigar_customs_match')
    op.drop_index(op.f('ix_blend_component_cigar_id'), table_name='blend_component')
    op.drop_table('blend_component')
    op.drop_index(op.f('ix_cigar_slug'), table_name='cigar')
    op.drop_index(op.f('ix_cigar_line_id'), table_name='cigar')
    op.drop_table('cigar')
    op.drop_index(op.f('ix_cigar_line_brand_id'), table_name='cigar_line')
    op.drop_table('cigar_line')
    op.drop_index(op.f('ix_customs_price_entry_raw_product_label'), table_name='customs_price_entry')
    op.drop_index(op.f('ix_customs_price_entry_raw_brand_label'), table_name='customs_price_entry')
    op.drop_index(op.f('ix_customs_price_entry_effective_date'), table_name='customs_price_entry')
    op.drop_table('customs_price_entry')
    op.drop_index(op.f('ix_brand_slug'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
