"""add cigar_package table

Revision ID: d1e416a9c5d7
Revises: 9f344dbacb5c
Create Date: 2026-05-25 01:05:39.316511+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e416a9c5d7'
down_revision: str | Sequence[str] | None = '9f344dbacb5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cigar_package',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cigar_id', sa.Uuid(), nullable=False),
    sa.Column('pack_size', sa.Integer(), nullable=False),
    sa.Column('source_domain', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigar.id'], name=op.f('fk_cigar_package_cigar_id_cigar'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cigar_package')),
    sa.UniqueConstraint('cigar_id', 'source_url', name='uq_cigar_package_cigar_source')
    )
    op.create_index(op.f('ix_cigar_package_cigar_id'), 'cigar_package', ['cigar_id'], unique=False)
    op.create_index(op.f('ix_cigar_package_source_domain'), 'cigar_package', ['source_domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cigar_package_source_domain'), table_name='cigar_package')
    op.drop_index(op.f('ix_cigar_package_cigar_id'), table_name='cigar_package')
    op.drop_table('cigar_package')
    # ### end Alembic commands ###
