"""customs multi country refactor

Revision ID: 6b78342bf049
Revises: 41ec706668a5
Create Date: 2026-05-25 03:17:36.448133+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b78342bf049'
down_revision: str | Sequence[str] | None = '41ec706668a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customs_source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('index_url', sa.String(length=2048), nullable=False),
    sa.Column('discovery_parser_name', sa.String(length=128), nullable=False),
    sa.Column('extraction_parser_name', sa.String(length=128), nullable=False),
    sa.Column('default_currency_code', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cron_expression', sa.String(length=64), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_publication_seen_ref', sa.String(length=256), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customs_source'))
    )
    op.create_index(op.f('ix_customs_source_code'), 'customs_source', ['code'], unique=True)
    op.create_index(op.f('ix_customs_source_country_code'), 'customs_source', ['country_code'], unique=False)
    op.create_table('customs_publication',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('regulator_reference', sa.String(length=256), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.String(length=2048), nullable=False),
    sa.Column('document_mime', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'FETCHED', 'PARSED', 'INGESTED', 'FAILED', 'SKIPPED', name='customs_publication_status'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('entries_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['customs_source.id'], name=op.f('fk_customs_publication_source_id_customs_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customs_publication')),
    sa.UniqueConstraint('source_id', 'regulator_reference', name='uq_customs_publication_source_ref')
    )
    op.create_index(op.f('ix_customs_publication_source_id'), 'customs_publication', ['source_id'], unique=False)
    op.add_column('customs_price_entry', sa.Column('publication_id', sa.Uuid(), nullable=False))
    op.add_column('customs_price_entry', sa.Column('country_code', sa.String(length=2), nullable=False))
    op.add_column('customs_price_entry', sa.Column('currency_code', sa.String(length=3), nullable=False))
    op.add_column('customs_price_entry', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('customs_price_entry', 'homologation_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('customs_price_entry', 'effective_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_customs_price_entry_country_code'), 'customs_price_entry', ['country_code'], unique=False)
    op.create_index(op.f('ix_customs_price_entry_publication_id'), 'customs_price_entry', ['publication_id'], unique=False)
    op.create_unique_constraint('uq_customs_price_entry_natural', 'customs_price_entry', ['publication_id', 'raw_brand_label', 'raw_product_label', 'packaging_description'])
    op.create_foreign_key(op.f('fk_customs_price_entry_publication_id_customs_publication'), 'customs_price_entry', 'customs_publication', ['publication_id'], ['id'], ondelete='CASCADE')
    op.drop_column('customs_price_entry', 'bo_reference')
    op.drop_column('customs_price_entry', 'source_file')
    op.drop_column('customs_price_entry', 'unit_price_eur')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customs_price_entry', sa.Column('unit_price_eur', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('customs_price_entry', sa.Column('source_file', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('customs_price_entry', sa.Column('bo_reference', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_customs_price_entry_publication_id_customs_publication'), 'customs_price_entry', type_='foreignkey')
    op.drop_constraint('uq_customs_price_entry_natural', 'customs_price_entry', type_='unique')
    op.drop_index(op.f('ix_customs_price_entry_publication_id'), table_name='customs_price_entry')
    op.drop_index(op.f('ix_customs_price_entry_country_code'), table_name='customs_price_entry')
    op.alter_column('customs_price_entry', 'effective_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('customs_price_entry', 'homologation_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('customs_price_entry', 'unit_price')
    op.drop_column('customs_price_entry', 'currency_code')
    op.drop_column('customs_price_entry', 'country_code')
    op.drop_column('customs_price_entry', 'publication_id')
    op.drop_index(op.f('ix_customs_publication_source_id'), table_name='customs_publication')
    op.drop_table('customs_publication')
    op.drop_index(op.f('ix_customs_source_country_code'), table_name='customs_source')
    op.drop_index(op.f('ix_customs_source_code'), table_name='customs_source')
    op.drop_table('customs_source')
    # ### end Alembic commands ###
